### ISSUE TITLE
It doesn't work in multiple connections

### ISSUE THREAD

**Issue by marcomd** [ibmdb/ruby-ibmdb#45]
Rails supports multiple connections, but these drivers change queries created by other drivers. You should them work only in the context of the model connection.

**Comment by arvindgu** [comment]
Could you please provide more details about the problem and your use case?  
Also request you to fill this form http://goo.gl/forms/EKzg7A6HZw

**Comment by marcomd** [comment]
Sure and thanks for the answer.
Ruby 2.1.7, Rails 4.2.4 and multiple connection, in this example SqlServer+DB2

The gemfile:

```ruby
#Sql Server
gem 'tiny_tds', '~> 0.7.0'
gem 'activerecord-sqlserver-adapter', '~> 4.2.0'
#DB2
gem 'ibm_db', '~> 3.0.0'
```

In the database.yml

```yml
default_ms: &default_ms
  adapter: sqlserver
  mode: dblib
  timeout: 5000
  encoding: UTF-8

default_db2: &default_db2
  adapter: ibm_db

development:
  <<: *default_ms
  host: myhost
  database: MY_DB_SQL
  username: my_username
  password: my_password

development_db2:
  <<: *default_db2
  database: MY_DB2
  username: my_username
  password: my_password
  host: my_host
  port: my_port
  schema: my_schema
```

The rails models:

```ruby
#Sqlserver model on the default connection:
class Foo < ActiveRecord::Base
end

#DB2 model on the db2 connection:
class Bar < ActiveRecord::Base
  establish_connection "#{Rails.env}_db2".to_sym
  self.table_name = 'MY_TABLE'
end
```
