### ISSUE TITLE
Error connecting to DB2

### ISSUE THREAD

**Issue by sterankin** [ibmdb/ruby-ibmdb#95]
I am receiving the following error in my Ruby on Rails application when attempting to connect to IBM DB2.

RuntimeError (Failed to connect to [EATUATDAT] due to: uncaught throw :"Connection failed: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: \"SSL\".  Communication API being used: \"SOCKETS\".  Location where the error was detected: \"\".  Communication function detecting the error: \"sqlccSSLSocketSetup\".  Protocol specific error code(s): \"414\", \"*\", \"*\".  SQLSTATE=08001 SQLCODE=-30081")

I have tried every possible type of database.yml file, here is an example:

```
development:
  adapter: ibm_db
  host: TEST.HOST.COM
  database: EATUATDAT
  schema: EATUATDAT
  username: user123
  password: pass123
  authentication: CLIENT
  port: 9471
  security: ssl
  timeout: 20000
```

What am I missing?
